version: "3"
services:
  postgres:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres

  mypg-admin:
    image: dpage/pgadmin4
    ports:
      - 80:80
    environment:
      - PGADMIN_DEFAULT_EMAIL=postgres@gmail.com
      - PGADMIN_DEFAULT_PASSWORD=postgres
    depends_on:
      - postgres

  my-app-django:
      build: .
      command: python manage.py runserver 0.0.0.0:8000 # we don't need this in dockerfile anymore
      ports:
        - 8000:8000
      volumes:
        - .:/code
      depends_on:
        - postgres
